server:
  port: 8002
spring:
  profiles: usa
  application:
    name: eureka-producer
  boot:
    admin:
      client:
        url: http://localhost:7001/admin  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: usa-east-zone
management:
  endpoints:
    web:
      exposure:
        include: "*" 
---
server:
  port: 8005
spring:
  profiles: ldn
  application:
    name: eureka-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: ldn-zone
---
server:
  port: 8010
spring:
  profiles: sgr
  application:
    name: eureka-producer
  boot:
    admin:
      client:
        url: http://localhost:7003/admin   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: sgr-zone
management:
  endpoints:
    web:
      exposure:
        include: "*" 