server:
  port: 7000
spring:
  profiles: default
  application:
    name: eureka-server.com
  boot:
    admin:
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: eureka-server.com
    appname: eureka-cluster
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF      
---
server:
  port: 7001
spring:
  profiles: usa
  boot:
    admin:
      context-path: /admin
eureka:
  instance:
    hostname: eureka-server-usa.com
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-ldn.com:7002/eureka/,http://eureka-server-sgr.com:7003/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF  
management:
  endpoints:
    web:
      exposure:
        include: "*"  
---
server:
  port: 7002
spring:
  profiles: ldn
  boot:
    admin:
      context-path: /admin
eureka:
  instance:
    hostname: eureka-server-ldn.com
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-usa.com:7001/eureka/,http://eureka-server-sgr.com:7003/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 7003
spring:
  profiles: sgr
  boot:
    admin:
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: eureka-server-sgr.com
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-ldn.com:7002/eureka/,http://eureka-server-usa.com:7001/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF 